#!/usr/bin/env python

import sys
import commands
import models

def get_command(command_name):
    for attrname in dir(commands):
        if "Command" not in attrname:
            continue
        attr = getattr(commands, attrname)
        if hasattr(attr, "command_name"):
            if attr.command_name == command_name:
                return attr
    return None

command_name = sys.argv[1]
args = sys.argv[2:]

CommandClass = get_command(command_name)
cmd = CommandClass()
cmd.run(args)
