#!/usr/bin/env python

import pdb
import sys
import commands
import models

def get_command(command_action, command_target):
    command_name = command_action + " " + command_target
    for attrname in dir(commands):
        
        if "Add" not in attrname and "List" not in attrname \
                                and "Append" not in attrname\
                                and "Delete" not in attrname\
                                and "Update" not in attrname:
            continue
        attr = getattr(commands, attrname)
        
        if hasattr(attr, "command_name"):
            
            if attr.command_name == command_name:
                
                return attr
    return None

command_action = sys.argv[1]
command_target = sys.argv[2]
args = sys.argv[3:]


CommandClass = get_command(command_action, command_target)

cmd = CommandClass()
cmd.run(args)
